version: '3.9'
services:
  worldofgames:
    image: icemanm/scores_img
    container_name: scores-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8777:5000"
    volumes:
      - "./MainScores.py:/app/MainScores.py"
      - "./score.txt:/app/score.txt"

